# Generated by Django 4.2.5 on 2023-09-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tecnologias', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('github', models.URLField()),
                ('imagen', models.ImageField(upload_to='portafolio')),
            ],
        ),
    ]
