# Generated by Django 4.2.5 on 2023-09-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='github',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
