# Generated by Django 4.2.5 on 2023-09-10 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='phone',
        ),
    ]
